<?php
namespace app\modules\mobile\controllers;
use yii\web\Controller;
use app\modules\mobile\models\M;
class AddressController extends Controller{
    public $layout = false;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($_COOKIE['username'])){
            echo "<script>alert('请先登录！');window.location.href='?m=m/login/index';</script>";
        }
    }
    public function actionIndex(){
        return $this->render("index");
    }
    public function actionAddress(){
        return $this->render("address");
    }
}