<?php
namespace app\modules\mobile\controllers;
use app\modules\mobile\models\M;
use yii\web\Controller;

class SettingController extends Controller{
    public $layout = false;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($_COOKIE['username'])){
            echo "<script>alert('请先登录！');window.location.href='?m=m/login/index';</script>";
        }
    }
    public function actionIndex(){
        return $this->render("index");
    }
    public function actionCommonproblem(){
        return $this->render("commonproblem");
    }
    public function actionCpdetail(){
       return $this->render("cpdetail") ;
    }
    public function actionAccountset(){
        return $this->render("accountset");
    }
    public function actionSignout(){
        setcookie("username","",time()-1);
        header("Location:?m=m/login/index");
    }
}