<?php
namespace app\modules\mobile\controllers;
use yii\web\Controller;
class UcController extends Controller{
    public $layout = false;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($_COOKIE['username'])){
            echo "<script>alert('请先登录！');window.location.href='?m=m/login/index';</script>";
        }
    }
    public function actionIndex(){
         $this->layout = "m_main";
         return $this->render("index");
    }
    public function actionUd(){
        return $this->render("ud");
    }
    public function actionCollection(){
        return $this->render("collection");
    }
    public function actionCoupon(){
        return $this->render("coupon");
    }
}